services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - ./nginx/arr.default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - media_network
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:${DUCKDNS_VERSION}
    container_name: duckdns
    env_file:
      - ./duckdns/duckdns.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./duckdns:/config
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/c/Media/Movies:/data/movies
      - /mnt/c/Media/Series:/data/series
    ports:
      - 8096:8096
    networks:
      - media_network
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://mayarr.duckdns.org
      - PUID=1000
      - PGID=1000

  jellyseerr:
    image: ghcr.io/seerr-team/seerr:${SEERR_VERSION}
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - BASE_URL=/requests
    volumes:
      - ./jellyseerr/config:/app/config
    ports:
      - 5055:5055
    networks:
      - media_network
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:${PROWLARR_VERSION}
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    networks:
      - media_network
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./radarr/config:/config
      - /mnt/c/Media/Movies:/data/movies
      - /mnt/c/Media/Downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - media_network
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./sonarr/config:/config
      - /mnt/c/Media/Series:/data/series
      - /mnt/c/Media/Downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - media_network
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:${GLUETEN_VERSION}
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VPN_TYPE=openvpn
      - VPNSP=surfshark
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - FIREWALL_LAN_INPUT_PORTS=8080
    volumes:
      - ./gluetun/config:/gluetun
    ports:
      - "8080:8080/tcp" 
    networks:
      - media_network
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - WEBUI_USERNAME=${QBIT_USER}
      - WEBUI_PASSWORD=${QBIT_PASS}
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/c/Media/Downloads:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
    driver: bridge